CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(12) NOT NULL,
  "age" int NOT NULL,
  "roles_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) NOT NULL,
  "description" varchar(150) NOT NULL,
  "teacher_id" int NOT NULL,
  "level_id" int NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(20) NOT NULL
);

CREATE TABLE "course_transitions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses_id" int NOT NULL,
  "course_videos_id" int NOT NULL
);

CREATE TABLE "user_transitions" (
  "id" SERIAL PRIMARY KEY,
  "users_id" int NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_table" varchar(35) NOT NULL,
  "url" varchar(30) NOT NULL,
  "categories_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_categories" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_roles" varchar(35) NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "course_transitions" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "course_transitions" ADD FOREIGN KEY ("course_videos_id") REFERENCES "course_videos" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "user_transitions" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "user_transitions" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "level" ("id");





INSERT INTO roles (name_roles) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO categories (name_categories) VALUES ('frontend'), ('backend'), ('full stack');

INSERT INTO users (name,email,password,age,roles_id) VALUES ('Andres rodriguez duran','Anrodriguez@academlo.com','duran@',18,1 ), ('Daniel caro torres','Danielcaro@academlo.com','torres@',20,1), ('Elibath del carmen zambrano','Elidelcarmen@academlo.com','zambrano@',35,3), ('Felipe grillo paredez','Felipegrillo@academlo.com','paredez@',19,1), ('Juan alvarado giraldo','Juanalvarado@academlo.com','giraldo@',27,1), ('Alejandra olazagasti','Alejaolazagasti@academlo.com','olazagasti@',28,2), ('Brenda gonzales','Brendagonzales@academlo.com','gonzales@',30,2), ('Ian rosas','Ianrosas@academlo.com','rosas@',29,2);

INSERT INTO level   (level) VALUES ('Basico'),('Intermedio'),('Avanzado');

INSERT INTO courses (title,description,teacher_id,level_id) VALUES ('Fundamentos','Aprenderas las bases de html, css y javascript',22,1),('React','Aprenderas de forma basica e intermedia sobre react',23,2),('nodejs','Aprenderas a crear tus propias Apis',24,3);

INSERT INTO user_transitions (users_id, courses_id) VALUES (17,1),(18,2),(19,3),(20,1),(21,2),(22,1),(23,2),(24,3);

INSERT INTO course_videos(title_table, url, categories_id) VALUES ('fundamentos de html','www.fundamentosdehtml.com',1),('fundamentos de css','www.fundamentosdecss.com',1),('fundamentos de javascript','www.fundamentdejavascript.com',1),('fundamentos de react','www.fundamentosdereact.com',2),('react a nivel intermedio','www.reactanivelintermedio.com',2),('fundamentos de nodejs','www.fundamentosdenodejs.com',3),('nodejs a nivel intermedio','www.nodesanivelintermedio.com',3);

INSERT INTO course_transitions (courses_id,course_videos_id) VALUES (1,1),(1,2),(1,3),(2,4),(2,5),(3,6),(3,7);



\c course_register;




